version: "3.4"
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    image: tabletennis/backend
    ports:
      - "9999:80"
    depends_on:
      - mssql
    volumes:
      #- "/root/Players/:/app/Players/"
      - "/Users/yuntinghou/tt/TableTennis4dView/backend/TableTennis4dView.API/Players/:/app/Players/"
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    image: tabletennis/frontend
    ports:
      - "3000:3000"
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
      - 1401:1401
    environment:
      SA_PASSWORD: "Giejoo8a!iyeefF"
      ACCEPT_EULA: "Y"
